version: '3.9'

services:
  app:
    build:
      context: ./backend
    container_name: fleetify_app
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    depends_on:
      - mysql
    env_file:
      - .env

  mysql:
    image: mysql:8.0
    container_name: fleetify_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fleetify
    ports:
      - "3307:3306"